<a href="https://colab.research.google.com/github/nhasibuan/dicoding-submission/blob/main/%5BKlasifikasi%5D_Submission_Akhir_BMLP_Norman_S_Hasibuan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Penting**
- Jangan menambahkan import libary atau function apa pun, selain yang sudah tersedia pada cell code.
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Ingat, tugas Anda hanyalah melengkapi code yang rumpang pada bagian yang sudah ditandai "________" saja.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **INFORMASI NOTEBOOK KLASIFIKASI**

Notebook ini membangun model klasifikasi menggunakan dataset hasil clustering (`data_clustering.csv`).
Kolom **Target** berisi label cluster yang akan diprediksi oleh model klasifikasi.

# **1. Import Library**
Semua library yang dibutuhkan harus **import** di **cell** ini, jika ada library yang dijalankan di cell lain maka **submission langsung ditolak**.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
import joblib

In [2]:
# Mount Google Drive untuk akses file
from google.colab import drive
drive.mount('/content/drive')

# Path folder submission di Google Drive (sama dengan notebook clustering)
DRIVE_FOLDER = '/content/drive/MyDrive'  # ubah jika folder berbeda
import os
SAVE_PATH = DRIVE_FOLDER
print('Drive mounted. SAVE_PATH:', SAVE_PATH)

Mounted at /content/drive
Drive mounted. SAVE_PATH: /content/drive/MyDrive

# **2. Memuat Dataset**

Gunakan dataset hasil clustering yang memiliki fitur **Target**.

- Jika tidak menerapkan Interpretasi Hasil Clustering [Advanced], gunakan `data_clustering.csv`.
- Jika menerapkan [Advanced], gunakan `data_clustering_inverse.csv`.

In [3]:
# Gunakan dataset hasil clustering yang memiliki fitur Target

### MULAI CODE ###

# Baca dari Google Drive (hasil export notebook clustering)
df = pd.read_csv(os.path.join(SAVE_PATH, 'data_clustering.csv'))

print(f'Dataset loaded: {df.shape[0]} baris, {df.shape[1]} kolom')
print(f'Kolom: {df.columns.tolist()}')

### SELESAI CODE ###

Dataset loaded: 1501 baris, 10 kolom
Kolom: ['TransactionAmount', 'TransactionType', 'Location', 'Channel', 'CustomerAge', 'CustomerOccupation', 'TransactionDuration', 'LoginAttempts', 'AccountBalance', 'Target']

In [4]:
# Tampilkan 5 baris pertama dengan function head

### MULAI CODE ###

df.head()

### SELESAI CODE ###

,TransactionAmount,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,Target
0,14.09,1,36,0,70.0,0,81.0,1.0,5112.21,3
1,376.24,1,15,0,68.0,0,141.0,1.0,13758.91,2
2,126.29,1,23,2,19.0,3,56.0,1.0,1122.35,0
3,184.50,1,33,2,26.0,3,25.0,1.0,8569.06,0
4,92.15,1,28,0,18.0,3,172.0,1.0,781.68,0

# **3. Pembagian Dataset dan Pemodelan Klasifikasi**

Pada tahap ini Anda akan:
1. Membagi dataset menggunakan `train_test_split()`.
2. Membangun model **Decision Tree** (wajib).
3. Menyimpan model Decision Tree sebagai `decision_tree_model.h5`.
4. Membangun model tambahan selain Decision Tree (opsional).
5. Evaluasi semua model.
6. Hyperparameter Tuning (opsional).
7. Menyimpan model terbaik hasil tuning sebagai `best_model_classification.h5`.

In [5]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.

### MULAI CODE ###

# Pisahkan fitur (X) dan label (y)
X = df.drop(columns=['Target'])
y = df['Target']

# Pembagian 80% train, 20% test dengan stratify agar distribusi kelas seimbang
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f'Ukuran data latih  : {X_train.shape}')
print(f'Ukuran data uji    : {X_test.shape}')
print(f'Distribusi Target (train):\n{y_train.value_counts().sort_index()}')
print(f'\nDistribusi Target (test):\n{y_test.value_counts().sort_index()}')

### SELESAI CODE ###

Ukuran data latih  : (1200, 9)
Ukuran data uji    : (301, 9)
Distribusi Target (train):
Target
0    225
1    257
2    298
3    313
4    107
Name: count, dtype: int64

Distribusi Target (test):
Target
0    56
1    65
2    75
3    78
4    27
Name: count, dtype: int64

## **3.1 Decision Tree Classifier**

In [6]:
# Buatlah model klasifikasi menggunakan Decision Tree

### MULAI CODE ###

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

print('=== Decision Tree ===')
print(f'Akurasi   : {accuracy_score(y_test, y_pred_dt):.4f}')
print(f'Presisi   : {precision_score(y_test, y_pred_dt, average="weighted", zero_division=0):.4f}')
print(f'Recall    : {recall_score(y_test, y_pred_dt, average="weighted", zero_division=0):.4f}')
print(f'F1-Score  : {f1_score(y_test, y_pred_dt, average="weighted", zero_division=0):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_pred_dt, zero_division=0))

### SELESAI CODE ###

=== Decision Tree ===
Akurasi   : 0.9668
Presisi   : 0.9671
Recall    : 0.9668
F1-Score  : 0.9669

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        56
           1       0.94      0.94      0.94        65
           2       1.00      0.99      0.99        75
           3       0.94      0.95      0.94        78
           4       0.96      1.00      0.98        27

    accuracy                           0.97       301
   macro avg       0.97      0.97      0.97       301
weighted avg       0.97      0.97      0.97       301

In [7]:
# Menyimpan Model

### MULAI CODE ###

joblib.dump(dt_model, 'decision_tree_model.h5')
joblib.dump(dt_model, os.path.join(SAVE_PATH, 'decision_tree_model.h5'))
print('decision_tree_model.h5 tersimpan lokal & Drive')

### SELESAI CODE ###

decision_tree_model.h5 tersimpan lokal & Drive

### **MULAI CODE OPSIONAL**

**Biarkan kosong jika tidak menerapkan kriteria opsional.**

Bagian ini mencakup:
- Model selain Decision Tree (misal: RandomForestClassifier)
- Evaluasi semua model
- Hyperparameter Tuning
- Simpan model terbaik

In [8]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree.
# (Contoh: RandomForestClassifier)

### MULAI CODE ###

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print('=== Random Forest ===')
print(f'Akurasi   : {accuracy_score(y_test, y_pred_rf):.4f}')
print(f'Presisi   : {precision_score(y_test, y_pred_rf, average="weighted", zero_division=0):.4f}')
print(f'Recall    : {recall_score(y_test, y_pred_rf, average="weighted", zero_division=0):.4f}')
print(f'F1-Score  : {f1_score(y_test, y_pred_rf, average="weighted", zero_division=0):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_pred_rf, zero_division=0))

### SELESAI CODE ###

=== Random Forest ===
Akurasi   : 0.9834
Presisi   : 0.9835
Recall    : 0.9834
F1-Score  : 0.9834

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        56
           1       0.97      0.98      0.98        65
           2       0.99      1.00      0.99        75
           3       0.97      0.97      0.97        78
           4       1.00      0.96      0.98        27

    accuracy                           0.98       301
   macro avg       0.99      0.98      0.98       301
weighted avg       0.98      0.98      0.98       301

In [9]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score
# pada seluruh algoritma yang sudah dibuat.

### MULAI CODE ###

results = {
    'Model': ['Decision Tree', 'Random Forest'],
    'Akurasi' : [
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_rf)
    ],
    'Presisi' : [
        precision_score(y_test, y_pred_dt, average='weighted', zero_division=0),
        precision_score(y_test, y_pred_rf, average='weighted', zero_division=0)
    ],
    'Recall'  : [
        recall_score(y_test, y_pred_dt, average='weighted', zero_division=0),
        recall_score(y_test, y_pred_rf, average='weighted', zero_division=0)
    ],
    'F1-Score': [
        f1_score(y_test, y_pred_dt, average='weighted', zero_division=0),
        f1_score(y_test, y_pred_rf, average='weighted', zero_division=0)
    ]
}

df_results = pd.DataFrame(results)
df_results = df_results.set_index('Model')
df_results = df_results.round(4)
print('=== Perbandingan Semua Model ===')
df_results

### SELESAI CODE ###

=== Perbandingan Semua Model ===

               Akurasi  Presisi  Recall  F1-Score
Model
Decision Tree   0.9668   0.9671  0.9668    0.9669
Random Forest   0.9834   0.9835  0.9834    0.9834

In [10]:
# Menyimpan Model Selain Decision Tree

### MULAI CODE ###

joblib.dump(rf_model, 'explore_RandomForest_classification.h5')
joblib.dump(rf_model, os.path.join(SAVE_PATH, 'explore_RandomForest_classification.h5'))
print('explore_RandomForest_classification.h5 tersimpan lokal & Drive')

### SELESAI CODE ###

explore_RandomForest_classification.h5 tersimpan lokal & Drive

## **3.2 Hyperparameter Tuning**

In [11]:
# Lakukan Hyperparameter Tuning dan Latih ulang.

### MULAI CODE ###

param_dist = {
    'n_estimators'      : [50, 100, 150, 200],
    'max_depth'         : [None, 5, 10, 15, 20],
    'min_samples_split' : [2, 5, 10],
    'min_samples_leaf'  : [1, 2, 4],
    'max_features'      : ['sqrt', 'log2', None]
}

rf_base = RandomForestClassifier(random_state=42)
tuning_model = RandomizedSearchCV(
    estimator=rf_base,
    param_distributions=param_dist,
    n_iter=20,
    cv=5,
    scoring='f1_weighted',
    n_jobs=-1,
    random_state=42,
    verbose=1
)
tuning_model.fit(X_train, y_train)

print(f'Best Parameters: {tuning_model.best_params_}')
print(f'Best CV F1-Score: {tuning_model.best_score_:.4f}')

### SELESAI CODE ###

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Best Parameters: {'n_estimators': 100, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 5}
Best CV F1-Score: 0.9741

In [12]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score
# pada algoritma yang sudah dituning.

### MULAI CODE ###

best_model = tuning_model.best_estimator_
y_pred_tuned = best_model.predict(X_test)

print('=== Random Forest (setelah Tuning) ===')
print(f'Akurasi   : {accuracy_score(y_test, y_pred_tuned):.4f}')
print(f'Presisi   : {precision_score(y_test, y_pred_tuned, average="weighted", zero_division=0):.4f}')
print(f'Recall    : {recall_score(y_test, y_pred_tuned, average="weighted", zero_division=0):.4f}')
print(f'F1-Score  : {f1_score(y_test, y_pred_tuned, average="weighted", zero_division=0):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_pred_tuned, zero_division=0))

# Perbandingan sebelum vs sesudah tuning
results_tuning = {
    'Model': ['Decision Tree', 'Random Forest', 'RF Tuned'],
    'Akurasi' : [
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_tuned)
    ],
    'Presisi' : [
        precision_score(y_test, y_pred_dt, average='weighted', zero_division=0),
        precision_score(y_test, y_pred_rf, average='weighted', zero_division=0),
        precision_score(y_test, y_pred_tuned, average='weighted', zero_division=0)
    ],
    'Recall'  : [
        recall_score(y_test, y_pred_dt, average='weighted', zero_division=0),
        recall_score(y_test, y_pred_rf, average='weighted', zero_division=0),
        recall_score(y_test, y_pred_tuned, average='weighted', zero_division=0)
    ],
    'F1-Score': [
        f1_score(y_test, y_pred_dt, average='weighted', zero_division=0),
        f1_score(y_test, y_pred_rf, average='weighted', zero_division=0),
        f1_score(y_test, y_pred_tuned, average='weighted', zero_division=0)
    ]
}

df_tuning = pd.DataFrame(results_tuning).set_index('Model').round(4)
print('\n=== Perbandingan Semua Model (termasuk Tuning) ===')
df_tuning

### SELESAI CODE ###

=== Random Forest (setelah Tuning) ===
Akurasi   : 0.9834
Presisi   : 0.9836
Recall    : 0.9834
F1-Score  : 0.9834

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        56
           1       0.98      0.97      0.98        65
           2       0.99      1.00      0.99        75
           3       0.96      0.99      0.97        78
           4       1.00      0.96      0.98        27

    accuracy                           0.98       301
   macro avg       0.99      0.98      0.98       301
weighted avg       0.98      0.98      0.98       301


=== Perbandingan Semua Model (termasuk Tuning) ===

               Akurasi  Presisi  Recall  F1-Score
Model
Decision Tree   0.9668   0.9671  0.9668    0.9669
Random Forest   0.9834   0.9835  0.9834    0.9834
RF Tuned        0.9834   0.9836  0.9834    0.9834

In [13]:
# Menyimpan Model hasil tuning

### MULAI CODE ###

joblib.dump(best_model, 'tuning_classification.h5')
joblib.dump(best_model, os.path.join(SAVE_PATH, 'tuning_classification.h5'))
print('tuning_classification.h5 tersimpan lokal & Drive')

joblib.dump(best_model, 'best_model_classification.h5')
joblib.dump(best_model, os.path.join(SAVE_PATH, 'best_model_classification.h5'))
print('best_model_classification.h5 tersimpan lokal & Drive')

### SELESAI CODE ###

tuning_classification.h5 tersimpan lokal & Drive
best_model_classification.h5 tersimpan lokal & Drive

### **SELESAI CODE OPSIONAL**

---
# End of Notebook